export { siteConfig } from "./site";
export { heroConfig } from "./hero";
export { aboutConfig } from "./about";
export { skillsConfig } from "./skills";
export { educationConfig } from "./education";
export { projectsConfig } from "./projects";
export { contactConfig } from "./contact";
export { navConfig } from "./nav";
export { seoConfig } from "./seo";
